
#ifndef __FILTER_H__
#define __FILTER_H__

/**
  * class HiPassFilter
  *
  * Originally generated by Umbrello
  */


#include "TimeData.h"

class Filter 
{
public:

  /**
   * Empty Constructor
   */
  Filter();

  /**
   * Empty Destructor
   */
  virtual ~Filter();

  /**
   * @return bool
   */
  static bool testClass();

protected:

  /** Column labels */
  string name;

public:

  /**
   * Default initailizer
   */
  void initAttributes();

};

#endif // __FILTER_H__
