#include "Filter.h"

/**
  * class Filter
  * Copyright 2014, Quakefinder
  * "$Id: Filter.cpp,v b1ae3e2c0bec 2014/12/09 16:42:57 qcvs $";
  *
  * Originally generated by Umbrello
 */


// Constructors/Destructors
//  

Filter::Filter ( ) {
initAttributes();
}

Filter::~Filter ( ) { }

//  
// Methods
//  


// Accessor methods
//  


// Other methods
//  

void Filter::initAttributes ( ) {
	name = "";
}

