#include "FreqData.h"

/**
  * class FreqData
  * Copyright 2014, Quakefinder
  * "$Id: FreqData.cpp,v b1ae3e2c0bec 2014/12/09 16:42:57 qcvs $";
  *
  * Originally generated by Umbrello
  */

// Constructors/Destructors
//  

// FreqData::FreqData ( ) {
// initAttributes();
// }

// FreqData::~FreqData ( ) { }

//  
// Methods
//  


// Accessor methods
//  


// Other methods
//  

void FreqData::initAttributes ( ) {
}

