
#ifndef __HIPASSFILTER_H__
#define __HIPASSFILTER_H__

/**
  * class HiPassFilter
  * Copyright 2014, Quakefinder
  * "$Id: HiPassFilter.h,v ee5036e83f4e 2015/04/02 19:18:28 cdunson $";
  *
  * Originally generated by Umbrello
  */

#include "Filter.h"


class HiPassFilter : public Filter
{
public:

  /**
   * Empty Constructor
   */
  HiPassFilter();

  /**
   * Full Constructor
   */
  HiPassFilter( const double &passF, const int &fLen );

  /**
   * Destructor
   */
  virtual ~HiPassFilter();

  /**
   * @return bool
   */
  static bool testClass();

protected:

  /** Knee frequency */
  double passFreq;
  /** Filter length in samples */
  int filtrLen;
  /** Group delay */
  double tossSecs;

public:

  /**
   * Default initailizer
   */
  void initAttributes();

  bool apply( const TimeData& src, TimeData& result ) const;

};

#endif // __HIPASSFILTER_H__
