#include "SpecData.h"

/**
  * class SpecData
  * Copyright 2014, Quakefinder
  * "$Id: SpecData.cpp,v b1ae3e2c0bec 2014/12/09 16:42:57 qcvs $";
  *
  * Originally generated by Umbrello
  */

// Constructors/Destructors
//  

// SpecData::SpecData ( ) {
// initAttributes();
// }

// SpecData::~SpecData ( ) { }

//  
// Methods
//  


// Accessor methods
//  


// Other methods
//  

void SpecData::initAttributes ( ) {
}

